#config_version=6

#modes/base/config/base.yaml


mode:
    start_events: ball_starting
    priority: 100

slide_player:
  mode_base_started: base


shots:
  sh_outlane_left:
    switch: s_outlane_left


variable_player:
  # placeholders
  sh_outlane_left_hit:
    score: 25 * current_player.playfield_multiplier
    #bonus_multiplier: 1



