#config_version=6

mode_settings:
    bonus_entries:
#        - entry: loops_completed
#          text: "Ranger Loops"
#          player_score_entry: ranger_loops_count
#          score: 10_000
#        - entry: songs_completed
#          text: "Songs Sung"
#          player_score_entry: total_songs
#          score: 5_000

