#config_version=6

slide_player:
    mode_attract_started: attract

show_player:
    mode_attract_started.1:
        attract_triangle_flash:
            speed: 4
        attract_arrow_sweep_left:
            speed: 6
        attract_arrow_sweep_right:
            speed: 6
