#config_version=6

#modes/attract/config/attract.yaml

show_player:
    mode_attract_started.1:
        attract_arrow_sweep_left:
            speed: 4
        attract_arrow_sweep_right:
            speed: 4
        attract_rollover_lanes:
            speed: 4
        attract_threebank_sweep:
            speed: 2
        attract_triangle_flash:
            speed: 4

hardware_sound_player:
    mode_attract_started.2:
        set_volume:
            action: set_volume
            value: "0.2"
        "FOURNOTEMELODIC.snd": # nick sound
            track: 1
            action: play_file
            platform_options:
                loop: true
                no_cache: false

#slide_player:
#    mode_attract_started: attract

