#config_version=6

mode:
    start_events: ball_started

ball_saves:
    ball_save_ball_save:
        active_time: 15s
        hurry_up_time: 5s
        timer_start_events: balldevice_bd_drain_ejecting_ball
        auto_launch: false
        balls_to_save: 1

show_player:
    ball_save_ball_save_ball_save_timer_start:
        ball_save_flash:
            key: ball_save
            speed: 2
    ball_save_ball_save_ball_save_hurry_up:
        ball_save_flash:
            key: ball_save
            speed: 4
    ball_save_ball_save_ball_save_disabled:
        ball_save: stop
