#config_version=6

### NOTE: Attempt at autorotating skillshot using roller lanes. 
### - with below config, skillshot starts after first ball (including if ejected from ball_save)
### , all three lanes light at once and do not flash
### , scoring works as expected (as if all 3 lanes are lit skillshots)
mode:
    start_events: start_mode_skillshot #, balldevice_bd_drain_ejecting_ball #ball_started #, start_mode_skill_shot
    stop_events: stop_mode_skillshot #, ball_ending
    priority: 100

event_player:
    timer_skillshot_rotate_stopped:
        - advance_skillshot_left{device.shots.skillshot_drop_left.state==1}
        - advance_skillshot_mid{device.shots.skillshot_drop_mid.state==1}
        - advance_skillshot_right{device.shots.skillshot_drop_right.state==1}
    skillshot_hit: stop_mode_skillshot
    playfield_active: stop_mode_skillshot|3s

shots:
    skillshot_drop_left:
        switch: s_rollover_upper_left
        advance_events: mode_skillshot_started, advance_skillshot_left
        profile: skillshot_profile
        show_tokens:
            light:
                l_rollover_upper_left
                #l_rollover_upper_left: ff
    skillshot_drop_mid:
        switch: s_rollover_upper_mid
        advance_events: mode_skillshot_started, advance_skillshot_mid
        profile: skillshot_profile
        show_tokens:
            light:
                l_rollover_upper_mid
                #l_rollover_upper_mid: ff
    skillshot_drop_right:
        switch: s_rollover_upper_right
        advance_events: mode_skillshot_started, advance_skillshot_right
        profile: skillshot_profile
        show_tokens:
            light:
              l_rollover_upper_right
              #l_rollover_upper_right: ff

shot_groups:
    skillshot:
        shots:
            - skillshot_drop_left
            - skillshot_drop_mid
            - skillshot_drop_right
        rotate_events: timer_skillshot_rotate_tick

timers:
    skillshot_rotate:
        tick_interval: 500ms
        start_running: true
        control_events:
            - event: balldevice_playfield_ball_enter #s_standup_upper_left_active
              action: stop

shot_profiles:
    skillshot_profile:
        advance_on_hit: false
        states:
            - name: off
              show: off
            - name: on
              show: on
            - name: lit
              show: flash

variable_player:
    skillshot_lit_hit:
        score: 50000




# mode:
#     start_events: ball_started
#     stop_events:
#         - skill_success
#         - skill_failed
#     priority: 500
# 
# shots:
#     skill_l:
#         switch: s_rollover_upper_left
#         profile: skill_shot_profile
#         advance_events: mode_skill_shot_started
#         show_tokens:
#             light: l_rollover_upper_left
#     skill_m:
#         switch: s_rollover_upper_mid
#         profile: skill_shot_profile
#         show_tokens:
#             light: l_rollover_upper_mid
#     skill_r:
#         switch: s_rollover_upper_right
#         profile: skill_shot_profile
#         show_tokens:
#             light: l_rollover_upper_right
# 
# shot_groups:
#     skill_shot:
#         shots: skill_l, skill_m, skill_r
#         rotate_left_events: c_flipper_left_main_active
#         rotate_right_events: c_flipper_right_main_active
# 
# shot_profiles:
#     skill_shot_profile:
#         states:
#             - name: unlit
#               show: off
#             - name: flashing
#               show: flash
#               #show_tokens:
#               #    light: ff
#               speed: 4
#             - name: lit
#               show: on
#       loop: true
# 
# variable_player:
#     skill_success:
#         score: 100000
# 
# timers:
#     skill_shot_timeout:
#         start_value: 0
#         end_value: 10
#         direction: up
#         tick_interval: 1s
#         start_running: false
#         control_events:
#             - action: start
#               event: balldevice_bd_drain_ejecting_ball
# 
# state_machines:
#     skill_shot_success:
#         debug: true
#         states:
#             start:
#                 label: Skill shot ready
#             success:
#                 label: Skill successful
#                 events_when_started: skill_success
#             failed:
#                 label: Skill failed
#                 events_when_started: skill_failed
#         transitions:
#             - source: start
#               target: success
#               events: skill_shot_flashing_hit
#             - source: start
#               target: failed
#               events: skill_shot_unlit_hit, timer_skill_shot_timeout_complete
# 
# 
# 
# 
# 
# 
