#config_version=6

mode:
  start_events: carousel_artist_meatloaf_selected
  stop_events: ball_ended
  priority: 130


hardware_sound_player:
  mode_meatloaf_started:
    "meatloaf_bat_out_of_hell.snd":
      track: 1
      action: play_file
      platform_options:
        loop: true
        no_cache: false
