#config_version=6

#config/config.yaml


###############################################################################
# hardware
###############################################################################
# NOTE: with APC, switch nbr. corresponds directly to number listed in orig.
# hardware manual from manufacturer. In some Williams cases, "special solenoids
# /switches" (flippers, jet bumpers, etc.) are used. For APC, solenoids 17-22
# have switch nbrs replaced with 65-70. Right/left flippers do not have their
# button switches in mpf config, and use solenoids 23/24 respectively.
# lisy docs (Section "Hardware rules for solenoids with APC"):
#   - https://lisy.dev/swrep/LISY/LISY_user%20manual_v5.27-67a.pdf
# APC docs: https://github.com/AmokSolderer/APC/blob/master/DOC/RunGame.md
# Time Warp manual: https://www.ipdb.org/files/2568/Williams_1979_Time_Warp_English_Manual_no_schematics.pdf

hardware:
    platform: lisy

lisy:
    connection: serial
    port: /dev/ttyACM0
    baud: 115200
    #debug: true #can make game run slowly

# platform/hardware type (lisy/APC-specific)
digital_outputs:
    game_over_relay:
        number: 25
        type: driver
        enable_events: ball_started
        disable_events: ball_will_end

## use APC sdcard for sounds
hardware_sound_systems:
    default:
        label: APC

# play sounds via files on APC sdcard (action name should be "<FILENAME>.SND:")
hardware_sound_player:
    game_start:
        set_volume:
            action: set_volume
            value: 0.2
        "timewarpv2.snd": # time warp song, reduced 10db via audacity
        #"timewarp10minus.snd": # time warp song, reduced 10db via audacity
        #"music.snd": # filename on sdcard. using "music.snd" enables using background track on orig game rom
            track: 1
            action: play_file
            platform_options:
                loop: true
                no_cache: false
    game_ending:
        action: stop
        set_volume:
            action: set_volume
            value: 0


# various sound files for Time Warp on APC sdcard
        #"0_00.snd": # single short tone, either warning or switch or menu back
        #"0_0a.snd": # optimistic low to high, good for bank resets
        #"0_0b.snd": # sounds like a phaser, lowish. good for outlanes or slingshots
        #"0_0e_001.snd": # low background tone (several seconds, would require loop to be constant)
        #"0_0e_002.snd": # low, higher than 1 background tone (several seconds, would require loop to be constant)
        #"0_0f.snd": # multiple high tones, long
        #"0_01.snd": # # single short tone, either warning or switch or menu confirm
        # "0_1a.snd": # short high pitched tones, good for outlanes, maybe drop targets
        #"0_1b.snd": # low, short low-to-medhigh ascent, maybe good for jet bumpers
        #"0_1c.snd": # medium short phaser, good for target switches or kickouts
        #"0_1d.snd": # medium, low short phaser descent
        #"0_1e.snd": # med short phaser, very slight low to high
        #"0_02.snd": # single short tone, either warning or switch or menu confirm
        #"0_03.snd": # quick high ting (service button)
        #"0_04.snd": # short, med-high service tone
        #"0_05.snd": # short, med service tone
        #"0_06.snd": # short, med-low service tone
        #"0_07.snd": # very long loud descent phaser sound. dont use this unless for like a wizard mode
        #"0_08.snd": # medium, med-length phaser (good for key targets, dt resets, completions, etc.)
        #"0_09.snd": # sounds like crash/blast. good for outhole/outlanes
        #"0_10.snd": # medium-length (loud) echoing beep
        #"0_11.snd": # short tone burst, good for outlanes, single switches, rollovers
        #"0_12.snd": # short length high (quieter) echoing beep
        #"0_13.snd": # short low to high, good for bullseye or kickouts
        #"0_14.snd": # long repeating siren, good for tilt?
        #"0_15.snd": # short high, descending phaser, good for switch
        #"0_16.snd": # loud, med-length echoing boing. good for hard, key target switches
        #"0_17.snd": # echoing burn/crash. good for ball end or game over
        #"0_18.snd": # dissonent short phaser. good for target dropdowns
        #"0_19.snd": # long, loud dissonant sound. maybe good for game over or tilt



## virtual platform (when running without the physical hardware)
virtual_platform_start_active_switches: s_outhole
virtual_segment_display_connector:
    segment_displays:
        - info_display
        - player1_display
        - player2_display
        - player3_display
        - player4_display


###############################################################################
# game modes & player variables
###############################################################################

# modes: anything that has a folder in modes/ should be listed here
modes:
    - attract
    - ball_save
    - base
    - bonus
    - fivebank
    - jet_bumpers
    #(autorotating lanes skillshot. scoring works, not autorotate.
    # skillshot resets if made and drained within ball_save window)
    #- skillshot
    - rollover_lanes
    - threebank
    - tilt

# player variables: set the initial state of variables used by players when game starts
player_vars:
    playfield_multiplier:
        value_type: int
        initial_value: 1


###############################################################################
# switches
###############################################################################

switches:
    ## (mostly) admin switches

    ### flipper coils hardwired via "special solenoid" & uses APC/lisy hardware
    ### rules, switch config not needed.
    #s_flipper_left:
    #    number:
    #    tags: left_flipper
    #s_flipper_right:
    #    number:
    #    tags: right_flipper

    s_tilt_plumb_bob:
        number: 1
        ignore_window_ms: 200
        tags: tilt_warning
    s_tilt_ball_roll:
        number: 2
    s_start_button:
        number: 3
        tags: start
    s_coin_open_right:
        number: 4
    s_coin_center:
        number: 5
    s_coin_left:
        number: 6
    s_tilt_slam:
        number: 7
    s_high_score_reset:
        number: 8
    s_outhole:
        number: 9

    ## playfield switches
    ### upper playfield
    s_standup_upper_right:
        number: 10
        tags: playfield_active
    s_standup_upper_left:
        number: 11
        tags: playfield_active
    s_rollover_upper_left:
        number: 12
        tags: playfield_active
    s_rollover_upper_mid:
        number: 13
        tags: playfield_active
    s_rollover_upper_right:
        number: 14
        tags: playfield_active
    s_eject_hole_upper:
        number: 15
    s_target_upper_right:
        number: 16
        tags: playfield_active
    s_target_upper_left:
        number: 17
        tags: playfield_active

    ## (mostly) mid playfield
    s_rollover_inlane_right:
        number: 18
        tags: playfield_active

    ### williams used "special solenoids/switches" for a while. For APC, switch
    ### nbrs 65-70 correspond to coils 17-22, respectively. Replace switch nbr
    ### from manual with special switch nbr for mpf.
    s_jet_bumper_left_top:
        number: 65 #19 in manual
    s_jet_bumper_left_mid:
        number: 66 #20 in manual
    s_jet_bumper_left_bottom:
        number: 67 #21 in manual
    s_jet_bumper_right_mid:
        number: 68 #22 in manual
    s_jet_bumper_right:
        number: 69 #23 in manual

    s_eject_hole_mid:
        number: 24
    s_5bank_drop_target_left:
        number: 25
    s_5bank_drop_target_left_mid:
        number: 26
    s_5bank_drop_target_mid:
        number: 27
    s_5bank_drop_target_right_mid:
        number: 28
    s_5bank_drop_target_right:
        number: 29
    s_5bank_drop_target_series:
        number: 30
        ignore_window_ms: 500ms
    s_5bank_standup:
        number: 31
    s_standup_lower_right:
        number: 32
        tags: playfield_active
    s_3bank_drop_target_left:
        number: 33
    s_3bank_drop_target_mid:
        number: 34
    s_3bank_drop_target_right:
        number: 35
    s_3bank_drop_target_series:
        number: 36
        ignore_window_ms: 500ms
    s_3bank_standup:
        number: 37

    ## lower playfield
    s_standup_lower_left:
        number: 38
        tags: playfield_active
    s_rollover_outlane_right:
        number: 39
        tags: playfield_active
    s_rollover_outlane_left:
        number: 40
        tags: playfield_active
    s_slingshot_lower_right:
        number: 41
    s_slingshot_lower_left:
        number: 42
    s_tilt_lower_playfield:
        number: 43
    s_rollover_inlane_left:
        number: 44
        tags: playfield_active

################################################################################
# coils/solenoids
################################################################################
# NOTE: see note in switches section about APC/lisy-specific values.
# - Flipper coils only, not switches or mpf flipper configs, should be added for
# mpf.
# - Per APC/mpf docs coil number corresponds to number in orig. manual.
# - Time Warp drop targets work differently than mpf expects (series switch is
# active when all targets fall. Targets pass switch on way down and are
# inactive otherwise). As such, drop target pulse events are set

coils:
    c_eject_outhole:
        number: 1
        default_pulse_ms: 30
    c_eject_hole_upper:
        number: 2
        default_pulse_ms: 30
    c_eject_hole_mid:
        number: 3
        default_pulse_ms: 30
    c_3bank_drop_target_reset:
        number: 4
        default_pulse_ms: 100
        pulse_events:
            - machine_reset_phase_3
            - player_turn_started
            - s_3bank_drop_target_series_active
    c_5bank_drop_target_reset_top:
        number: 5
        default_pulse_ms: 75
        pulse_events:
            - machine_reset_phase_3
            - player_turn_started
            - s_5bank_drop_target_series_active
    c_5bank_drop_target_reset_bottom:
        number: 6
        default_pulse_ms: 100
        pulse_events:
            - machine_reset_phase_3
            - player_turn_started
            - s_5bank_drop_target_series_active
    c_slingshot_lower_right:
        number: 7
        default_pulse_ms: 30
    c_slingshot_lower_left:
        number: 8
        default_pulse_ms: 30
    c_sound1:
        number: 9
    c_sound2:
        number: 10
    c_sound3:
        number: 11
    c_sound4:
        number: 12
    c_sound5:
        number: 13
    c_credit_knocker:
        number: 14
    # c_notused:
    #    number: 15
    c_coin_lockout:
        number: 16
    c_jet_bumper_left_top:
        number: 17
        default_pulse_ms: 35
    c_jet_bumper_left_mid:
        number: 18
        default_pulse_ms: 35
    c_jet_bumper_left_bottom:
        number: 19
        default_pulse_ms: 35
    c_jet_bumper_right_mid:
        number: 20
        default_pulse_ms: 35
    c_jet_bumper_right:
        number: 21
        default_pulse_ms: 35
    # c_notused
    #    number: 22
    # time warp has single wound flipper coils
    c_flipper_right_main:
        number: 23
    # time warp has single wound flipper coils
    c_flipper_left_main:
        number: 24

################################################################################
# lights
################################################################################
# NOTE: see swithces note. number comes from lamp/matrix table in orig. manual,
# from top left down in Time Warp manual.

lights:
    #l_notused:
    #    number: 1
    l_triangle1:
        number: 2
    l_triangle2:
        number: 3
    l_triangle3:
        number: 4
    l_triangle4:
        number: 5
    l_triangle5:
        number: 6
    l_triangle6:
        number: 7
    l_triangle7:
        number: 8
    l_triangle8:
        number: 9
    l_triangle9:
        number: 10
    l_triangle10:
        number: 11
    l_triangle11:
        number: 12
    l_triangle12:
        number: 13
    l_rollover_upper_left:
        number: 14
    l_rollover_upper_mid:
        number: 15
    l_rollover_upper_right:
        number: 16
    l_eject_hole_left_1bottom:
        number: 17
    l_eject_hole_left_2:
        number: 18
    l_eject_hole_left_3:
        number: 19
    l_eject_hole_left_4top:
        number: 20
    l_x2:
        number: 21
    l_x3:
        number: 22
    l_x5:
        number: 23
    l_x10:
        number: 24
    l_rollover_lanes:
        number: 25
    l_arrow_right_1bottom:
        number: 26
    l_arrow_right_2:
        number: 27
    l_arrow_right_3:
        number: 28
    l_arrow_right_4top:
        number: 29
    l_bullseye_special:
        number: 30
    l_outlane_left:
        number: 31
    l_outlane_right:
        number: 32
    l_3bank_1bottom:
        number: 33
    l_3bank_2:
        number: 34
    l_3bank_3mid:
        number: 35
    l_3bank_4:
        number: 36
    l_3bank_5top:
        number: 37
    l_ballsave:
        number: 38
    l_jet_bumper_left_top:
        number: 39
    l_jet_bumper_left_mid:
        number: 40
    l_jet_bumper_left_bottom:
        number: 41
    l_jet_bumper_right_mid:
        number: 42
    l_jet_bumper_right:
        number: 43
    l_arrow_left_1bottom:
        number: 44
    l_arrow_left_2:
        number: 45
    l_arrow_left_3:
        number: 46
    l_arrow_left_4top:
        number: 47
    l_5bank_1:
        number: 48
    l_inlanes:
        number: 49
    l_1canplay:
        number: 50
    l_2canplay:
        number: 51
    l_3canplay:
        number: 52
    l_4canplay:
        number: 53
    l_match:
        number: 54
    l_ball_in_play:
        number: 55
    l_credits_playfield:
        number: 56
    l_player_up_1:
        number: 57
    l_player_up_2:
        number: 58
    l_player_up_3:
        number: 59
    l_player_up_4:
        number: 60
    l_tilt:
        number: 61
    l_game_over:
        number: 62
    l_same_player_again_backbox:
        number: 63
    l_high_score_to_date:
        number: 64

################################################################################
# playfield actions & such
################################################################################
## ball devices (anything that holds & releases a ball, including the playfield
## which "holds a ball")

ball_devices:
    bd_drain:
        ball_switches: s_outhole
        eject_coil: c_eject_outhole
        tags: drain, home, trough
        eject_timeouts: 3s

    bd_eject_hole_upper:
        ball_switches: s_eject_hole_upper
        eject_coil: c_eject_hole_upper
        eject_timeouts: 3s

    bd_eject_hole_mid:
        ball_switches: s_eject_hole_mid
        eject_coil: c_eject_hole_mid
        eject_timeouts: 3s

## playfield
playfields:
    playfield:
        default_source_device: bd_drain
        tags: default

## autofire coils (things that fire immediately when switch is hit)
autofire_coils:
    slingshot_left:
        coil: c_slingshot_lower_left
        switch: s_slingshot_lower_left
    slingshot_right:
        coil: c_slingshot_lower_right
        switch: s_slingshot_lower_right
    jet_bumper_left_top:
        coil: c_jet_bumper_left_top
        switch: s_jet_bumper_left_top
    jet_bumper_left_mid:
        coil: c_jet_bumper_left_mid
        switch: s_jet_bumper_left_mid
    jet_bumper_left_bottom:
        coil: c_jet_bumper_left_bottom
        switch: s_jet_bumper_left_bottom
    jet_bumper_right_mid:
        coil: c_jet_bumper_right_mid
        switch: s_jet_bumper_right_mid
    jet_bumper_right:
        coil: c_jet_bumper_right
        switch: s_jet_bumper_right


## drop targets
### NOTE: drop targets/banks still not working as expected using mpf configs,
### Time Warp drop target switches seem to be off when up/down and trigger
### while falling. Series switch is active when all targets are down.

## flippers
### NOTE: due to communication delay b/w mpf and APC, hardware rules are used
### and flipper configs not needed/possible as with other platforms

################################################################################
## displays
################################################################################
segment_displays:
    info_display:
        number: 0
        platform: lisy
        size: 4
    player1_display:
        number: 1
        platform: lisy
        size: 6
    player2_display:
        number: 2
        platform: lisy
        size: 6
    player3_display:
        number: 3
        platform: lisy
        size: 6
    player4_display:
        number: 4
        platform: lisy
        size: 6

segment_display_player:
    # empty all displays on game start and setup info display
    game_start:
        info_display:
            text: "{current_player.ball:d}"
        player1_display:
            text: ""
        player2_display:
            text: ""
        player3_display:
            text: ""
        player4_display:
            text: ""

    # show score when adding players
    player_added.1{num==1}:
        player1_display:
            text: "{players[0].score:d}"
    player_added.2{num==2}:
        player2_display:
            text: "{players[1].score:d}"
    player_added.3{num==3}:
        player3_display:
            text: "{players[2].score:d}"
    player_added.4{num==4}:
        player4_display:
            text: "{players[3].score:d}"

    # clear only info display after game
    game_ended:
        info_display:
            text: ""
    game_ended{machine.player1_score > 0}:
        player1_display:
            text: "{machine.player1_score:d}"
    game_ended{machine.player2_score > 0}:
        player2_display:
            text: "{machine.player2_score:d}"
    game_ended{machine.player3_score > 0}:
        player3_display:
            text: "{machine.player3_score:d}"
    game_ended{machine.player4_score > 0}:
        player4_display:
            text: "{machine.player4_score:d}"

    #flash display on player turn
    player_turn_started.1{number==1}:
        player1_display:
            action: flash
    player_turn_ended.2{number==1}:
        player1_display:
            action: no_flash
    player_turn_started.3{number==2}:
        player2_display:
            action: flash
    player_turn_ended.4{number==2}:
        player2_display:
            action: no_flash
    player_turn_started.5{number==3}:
        player3_display:
            action: flash
    player_turn_ended.6{number==3}:
        player3_display:
            action: no_flash
    player_turn_started.7{number==4}:
        player4_display:
            action: flash
    player_turn_ended.8{number==4}:
        player4_display:
            action: no_flash

