#config_version=6

###############################################################################
# hardware
###############################################################################

## hardware
hardware:
    platform: smart_virtual

#hardware:
#    platform: lisy

#lisy:
#    connection: serial
#    port: # com1 #TODO figure out what to put here
#    baud: 115200
#    debug: true # log leve debug. can make game run slowly


###############################################################################
# game modes
###############################################################################

modes:
    #- attract
    - base
    #- bonus
    #- skillshot

###############################################################################
# switches
###############################################################################

switches:
    ## (mostly) admin switches
    s_flipper_left: # switch TBD
        number: #46
        tags: left_flipper
    s_flipper_right: # switch TBD
        number: #45
        tags: right_flipper
    s_tilt_plumb_bob: # switch 1
        number: 1
    s_tilt_ball_roll: # switch 2
        number: 2
    s_start_button: # switch 3
        number: 3
        tags: start
    s_coin_open_right: # switch 4
        number: 4
    s_coin_center: # switch 5
        number: 5
    s_coin_left: # switch 6
        number: 6
    s_tilt_slam: # switch 7
        number: 7
    s_high_score_reset: # switch 8
        number: 8
    s_outhole: # switch 9
        number: 9

    ## playfield switches
    # upper playfield
    s_standup_upper_right: # switch 10
        number: 10
        tags: playfield_active
    s_standup_upper_left: # switch 11
        number: 11
        tags: playfield_active
    s_rollover_upper_left: # switch 12
        number: 12
        tags: playfield_active
    s_rollover_upper_mid: # switch 13
        number: 13
        tags: playfield_active
    s_rollover_upper_right: # switch 14
        number: 14
        tags: playfield_active
    s_eject_hole_upper: # switch 15
        number: 15
    s_target_upper_right: # switch 16
        number: 16
        tags: playfield_active
    s_target_upper_left: # switch 17
        number: 17
        tags: playfield_active

    # (mostly) mid playfield
    s_rollover_inlane_right: # switch 18
        number: 18
        tags: playfield_active
    s_jet_bumper_left_top: # switch 19
        number: 19
    s_jet_bumper_left_mid: # switch 20
        number: 20
    s_jet_bumper_left_bottom: # switch 21
        number: 21
    s_jet_bumper_right_mid: # switch 22
        number: 22
    s_jet_bumper_right: # switch 23
        number: 23
    s_eject_hole_mid: # switch 24
        number: 24
    s_5bank_drop_target_left: # switch 25
        number: 25
    s_5bank_drop_target_left_mid: # switch 26
        number: 26
    s_5bank_drop_target_mid: # switch 27
        number: 27
    s_5bank_drop_target_right_mid: # switch 28
        number: 28
    s_5bank_drop_target_right: # switch 29
        number: 29
    s_5bank_drop_target_series: # switch 30
        number: 30
    s_5bank_standup: # switch 31
        number: 31
    s_standup_lower_right: # switch 32
        number: 32
        tags: playfield_active
    s_3bank_drop_target_left: # switch 33
        number: 33
    s_3bank_drop_target_mid: # switch 34
        number: 34
    s_3bank_drop_target_right: # switch 35
        number: 35
    s_3bank_drop_target_series: # switch 36
        number: 36
    s_3bank_standup: # switch 37
        number: 37

    # lower playfield
    s_standup_lower_left: # switch 38
        number: 38
        tags: playfield_active
    s_rollover_outlane_right: # switch 39
        number: 39
        tags: playfield_active
    s_rollover_outlane_left: # switch 40
        number: 40
        tags: playfield_active
    s_kicker_lower_right: # switch 41
        number: 41
    s_kicker_lower_left: # switch 42
        number: 42
    s_tilt_lower_playfield: # switch 43
        number: 43
    s_rollover_inlane_left: # switch 44
        number: 44
        tags: playfield_active

#keyboard:
#    k:
#        switch: s_flipper_left
#    l:
#        switch: s_flipper_right
#    s:
#        switch: s_start_button
#    b:
#        switch: s_standup_upper_left


################################################################################
# coils/solenoids
################################################################################

# comments indicate coil number in time warp manual
coils:
    c_eject_outhole: # coil 1
        number: 1
        default_pulse_ms: 30
    c_eject_hole_upper: # coil 2
        number: 2
        default_pulse_ms: 30
    c_eject_hole_mid: # coil 3
        number: 3
        default_pulse_ms: 30
    c_3bank_drop_target_reset: # coil 4
        number: 4
        default_pulse_ms: 30
    c_5bank_drop_target_reset_top: # coil 5
        number: 5
        default_pulse_ms: 30
    c_5bank_drop_target_reset_bottom: # coil 6
        number: 6
        default_pulse_ms: 30
    c_kicker_lower_right: # coil 7
        number: 7
        default_pulse_ms: 30
    c_kicker_lower_left: # coil 8
        number: 8
        default_pulse_ms: 30
    c_sound1: # coil 9
        number: 9
    c_sound2: # coil 10
        number: 10
    c_sound3: # coil 11
        number: 11
    c_sound4: # coil 12
        number: 12
    c_sound5: # coil 13
        number: 13
    c_credit_knocker: # coil 14
        number: 14
    # c_notused: # coil 15
    #    number: 15
    c_coin_lockout: # coil 16
        number: 16
    c_jet_bumper_left_top: # coil 17
        number: 17
        default_pulse_ms: 30
    c_jet_bumper_left_mid: # coil 18
        number: 18
        default_pulse_ms: 30
    c_jet_bumper_left_bottom: # coil 19
        number: 19
        default_pulse_ms: 30
    c_jet_bumper_right_mid: # coil 20
        number: 20
        default_pulse_ms: 30
    c_jet_bumper_right: # coil 21
        number: 21
        default_pulse_ms: 30
    # c_notused # coil 22
    #    number: 22
    c_flipper_right_main:
        number: 23
        default_pulse_ms: 30
        default_hold_power: 0.25
    # remove hold if single wound coil
    #c_flipper_right_hold:
    #    number: #TBD
    #    allow_enable: true
    c_flipper_left_main:
        number: 24
        default_pulse_ms: 30
        default_hold_power: 0.25
    # remove hold if single wound coil
    #c_flipper_left_hold:
    #    number: #TBD
    #    allow_enable: true


################################################################################
# lights
################################################################################



################################################################################
# playfield(s) & such
################################################################################

##ball devices (anything that holds & releases a ball, including the playfield which "holds a ball")
ball_devices:
    bd_drain:
        ball_switches: s_outhole
        eject_coil: c_eject_outhole
        tags: drain, home, trough
        eject_timeouts: 3s

    bd_eject_hole_upper:
        ball_switches: s_eject_hole_upper
        eject_coil: c_eject_hole_upper
        eject_timeouts: 3s

    bd_eject_hole_mid:
        ball_switches: s_eject_hole_mid
        eject_coil: c_eject_hole_mid
        eject_timeouts: 3s

#ball_saves:
#    default:
#        active_time: 10s
#        hurry_up_time: 2s
#        grace_period: 3s
##        enable_events: #TODO  mode_base_started
##        timer_start_events: #TODO balldevice_plunger_lane_ball_eject_success
#        auto_launch: false
#        balls_to_save: 1
#        debug: true

## playfield
playfields:
    playfield:
        default_source_device: bd_drain
        tags: default

## flippers
flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        #hold_coil: c_flipper_left_hold # remove if single wound coil
        activation_switch: s_flipper_left
        #enable_events: machine_reset_phase_3 # temporary. enables flippers immediately with machine start
        #label: Left Flipper
    right_flipper:
        main_coil: c_flipper_right_main
        #hold_coil: c_flipper_right_hold # remove if single wound coil
        activation_switch: s_flipper_right
        #enable_events: machine_reset_phase_3 # temporary. enables flippers immediately with machine start
        #label: Right Flipper

## autofire coils (things that fire immediately when switch is hit)
autofire_coils:
    kicker_left:
        coil: c_kicker_lower_left
        switch: s_kicker_lower_left
    kicker_right:
        coil: c_kicker_lower_right
        switch: s_kicker_lower_right
    jet_bumper_left_top:
        coil: c_jet_bumper_left_top
        switch: s_jet_bumper_left_top
    jet_bumper_left_mid:
        coil: c_jet_bumper_left_mid
        switch: s_jet_bumper_left_mid
    jet_bumper_left_bottom:
        coil: c_jet_bumper_left_bottom
        switch: s_jet_bumper_left_bottom

## drop targets
drop_targets:
    fivebank_drop_target_left:
        switch: s_5bank_drop_target_left
    fivebank_drop_target_left_mid:
        switch: s_5bank_drop_target_left_mid
    fivebank_drop_target_mid:
        switch: s_5bank_drop_target_mid
    fivebank_drop_target_right_mid:
        switch: s_5bank_drop_target_right_mid
    fivebank_drop_target_right:
        switch: s_5bank_drop_target_right

    threebank_drop_target_left:
        switch: s_3bank_drop_target_left
    threebank_drop_target_mid:
        switch: s_3bank_drop_target_mid
    threebank_drop_target_right:
        switch: s_3bank_drop_target_right

drop_target_banks:
    five_bank_drop_target:
        drop_targets: fivebank_drop_target_left, fivebank_drop_target_left_mid, fivebank_drop_target_mid, fivebank_drop_target_right_mid, fivebank_drop_target_right
        reset_coils: c_5bank_drop_target_reset_top, c_5bank_drop_target_reset_bottom
        reset_on_complete: 10s

    three_bank_drop_target:
        drop_targets: threebank_drop_target_left, threebank_drop_target_mid, threebank_drop_target_right
        reset_coils: c_3bank_drop_target_reset
        reset_on_complete: 10s

################################################################################
## displays
################################################################################
# TODO: determine actual display numbers
segment_displays:
    info_display:
        number: 1
#        platform: lisy
        size: 6
    player1_display:
        number: 2
#        platform: lisy
        size: 6
    player2_display:
        number: 3
#        platform: lisy
        size: 6
    player3_display:
        number: 4
#        platform: lisy
        size: 6
    player4_display:
        number: 5
#        platform: lisy
        size: 6

virtual_segment_display_connector:
    segment_displays: info_display, player1_display, player2_display, player3_display, player4_display
# make info segment display only show numbers not hidden behind art
segment_display_player:
    mask_info_display:
        info_display:
            flash_mask: "_FF_FF"


#displays:
#    window:
#        width: 800
#        height: 600
#
#slides:
#    welcome_slide:
#        widgets:
#          - type: text
#            text: PINBALL!
#            font_size: 50
#            color: red
#          - type: rectangle
#            width: 240
#            height: 60
#    attract_started:
#        widgets:
#          - text: ATTRACT MODE
#            type: text



## virtual platform (when running without the physical hardware)

virtual_platform_start_active_switches: s_outhole




