#config_version=6

#modes/base/config/base.yaml


mode:
    start_events: ball_starting
    priority: 100

#event_player:
#    mode_base_started:
#        - start_mode_skillshot

#slide_player:
#    mode_base_started: base

#show_player:

shots:
    sh_target_left:
        switch: s_target_upper_left
    sh_target_right:
        switch: s_target_upper_right
        show_tokens:
            light: l_bullseye_special
        reset_events: ball_ending

variable_player:
    # variable values defined in shot_groups
    sh_target_left_hit:
        score: 1500
    sh_target_right_hit:
        score: 10000
    
    #s_target_upper_right_active:
    #    score: 10000
    #s_target_upper_left_active:
    #    score: 500

    # placeholders
    s_standup_upper_right_active:
        score: 25
        #bonus_multiplier: 1
    s_standup_upper_left_active:
        score: 25
    s_eject_hole_upper_active:
        score: 500

    s_eject_hole_mid_active:
        score: 500
    s_5bank_drop_target_left_active:
        score: 50
    s_5bank_drop_target_left_mid_active:
        score: 50
    s_5bank_drop_target_mid_active:
        score: 50
    s_5bank_drop_target_right_mid_active:
        score: 50
    s_5bank_drop_target_right_active:
        score: 50
    #s_5bank_drop_target_series_active:
    #    score: 50
    s_5bank_standup_active:
        score: 75
    s_standup_lower_right_active:
        score: 50
    s_standup_lower_left_active:
        score: 50
    s_rollover_outlane_right_active:
        score: 5000
    s_rollover_outlane_left_active:
        score: 5000
    s_rollover_inlane_left_active:
        score: 25
    s_rollover_inlane_right_active:
        score: 25

hardware_sound_player:
    ## check machine config for notes on snd files"

    # event-based sounds
    ball_will_end:
        "FOURNOTEMELODIC.snd": # nick sound
            track: 2
            action: play_file
            platform_options:
                loops: 2
                no_cache: false


    # "regular" switch/rollover hits
    s_standup_upper_left_active:
        #"4-note-melodic_1.snd": # nick sound
        "0_11.snd": # short tone burst, good for outlanes, single switches, rollovers
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false
    s_standup_upper_right_active:
        #"A-SFX.snd": # nick sound
        "0_11.snd": # short tone burst, good for outlanes, single switches, rollovers
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false

    s_target_upper_left_active:
        #"A-SFX-metallic.snd": # nick sound
        "0_08.snd": # medium, med-length phaser (good for key targets, dt resets, completions, etc.)
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false
    s_target_upper_right_active:
        #"A-sharp-warble-drone.snd": # nick sound
        "0_16.snd": # loud, med-length echoing boing. good for hard, key target switches
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false

    s_rollover_upper_left_active:
        #"FOURNOTEMELODIC.snd": # nick sound
        "0_11.snd": # short tone burst, good for outlanes, single switches, rollovers
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false
    s_rollover_upper_mid_active:
        #"FOURNOTEMELODIC.snd": # nick sound
        "0_11.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false
    s_rollover_upper_right_active:
        #"melodicsynth-pattern-8Bar-76bpm1.snd": # nick sound
        "0_11.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false

    s_eject_hole_upper_active:
        "0_1c.snd": # medium short phaser, good for target switches or kickouts
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false
    s_eject_hole_mid_active:
        "0_1c.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false

    s_standup_lower_left_active:
        "0_11.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false
    s_standup_lower_right_active:
        "0_11.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false

    s_slingshot_lower_left_active:
        "0_1a.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false
    s_slingshot_lower_right_active:
        "0_1a.snd": # short high pitched tones, good for outlanes, maybe drop targets
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false

    s_rollover_inlane_left_active:
        "0_0b.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false
    s_rollover_inlane_right_active:
        "0_0b.snd": #
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false

    s_rollover_outlane_left_active:
        "0_17.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false
    s_rollover_outlane_right_active:
        "0_17.snd": # echoing burn/crash. good for ball end or game over
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false

    s_5bank_drop_target_left_active:
        "0_1b.snd": #low, short low-to-medhigh ascent, maybe good for jet bumpers
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: true
    s_5bank_drop_target_left_mid_active:
        "0_1b.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: true
    s_5bank_drop_target_mid_active:
        "0_1b.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: true
    s_5bank_drop_target_right_mid_active:
        "0_1b.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: true
    s_5bank_drop_target_right_active:
        "0_1b.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: true
    s_5bank_drop_target_series_active:
        "0_0a.snd": # optimistic low to high, good for bank resets
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: true
    s_5bank_standup_active:
        "0_1b.snd": # low, short low-to-medhigh ascent, maybe good for jet bumpers
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: true


# NOTE: text-to-speech is a feature if using lisy as hardware sound player.
# interested to see if lisy can be set as hardware_sound_player for a mode to
# utilize text-to-speech via APC
#    s_eject_hole_upper_active:
#        text:
#            action: text_to_speech
#            value: "Plop!"
#            platform_operations:
#                loop: 2
#                no_cache: true
#    s_standup_upper_left_active:
#        text:
#            action: text_to_speech
#            value: "meat!"
#            platform_operations:
#                loop: false
#                no_cache: true
#    s_standup_upper_right_active:
#        text:
#            action: text_to_speech
#            value: "loaf!"
#            platform_operations:
#                loop: false
#                no_cache: true

