#config_version=6

mode:
    start_events: ball_starting
    priority: 100

shots:
    sh_target_left:
        switch: s_target_upper_left
    sh_target_right:
        switch: s_target_upper_right
        show_tokens:
            light: l_bullseye_special
#    sh_rollover_upper_left:
#        switch: s_rollover_upper_left
#        show_tokens:
#            light: l_rollover_upper_left
#    sh_rollover_upper_mid:
#        switch: s_rollover_upper_mid
#        show_tokens:
#            light: l_rollover_upper_mid
#    sh_rollover_upper_right:
#        switch: s_rollover_upper_right
#        show_tokens:
#            light: l_rollover_upper_right

#shot_groups:
#    rollover_lanes:
#        shots: sh_rollover_upper_left, sh_rollover_upper_mid, sh_rollover_upper_right
#        #rotate_left_events: sw_left_flipper
#        #rotate_right_events: sw_right_flipper
#        reset_events: rollover_lanes_complete

#    bumper_shots:
#        shots: bumper_shot_1, bumper_shot_2

slide_player:
    mode_base_started: base

variable_player:
    # variable values defined in shot_groups
    rollover_lanes_unlit_hit:
        score: 1000
    rollover_lanes_lit_hit:
        score: 3000

    # switches tied to points
    s_target_upper_right_active:
        score: 10000
    s_target_upper_left_active:
        score: 500

    # single-point placeholders
    s_standup_upper_right_active:
        score: 1
        #bonus_multiplier: 1
    s_standup_upper_left_active:
        score: 1
    #s_rollover_upper_left_active:
    #    score: 1
    #s_rollover_upper_mid_active:
    #    score: 1
    #s_rollover_upper_right_active:
    #    score: 1
    s_eject_hole_upper_active:
        score: 1
    s_jet_bumper_left_top_active:
        score: 1
    s_jet_bumper_left_mid_active:
        score: 1
    s_jet_bumper_left_bottom_active:
        score: 1
    s_jet_bumper_right_mid_active:
        score: 1
    s_jet_bumper_right_active:
        score: 1
    s_eject_hole_mid_active:
        score: 1
    s_5bank_drop_target_left_active:
        score: 1
    s_5bank_drop_target_left_mid_active:
        score: 1
    s_5bank_drop_target_mid_active:
        score: 1
    s_5bank_drop_target_right_mid_active:
        score: 1
    s_5bank_drop_target_right_active:
        score: 1
    s_5bank_drop_target_series_active:
        score: 1
    s_5bank_standup_active:
        score: 1
    s_standup_lower_right_active:
        score: 1
    s_standup_lower_left_active:
        score: 1
    s_3bank_drop_target_left_active:
        score: 1
    s_3bank_drop_target_mid_active:
        score: 1
    s_3bank_drop_target_right_active:
        score: 1
    s_3bank_drop_target_series_active:
        score: 1
    s_3bank_standup_active:
        score: 1
    s_rollover_outlane_right_active:
        score: 1
    s_rollover_outlane_left_active:
        score: 1
    s_rollover_inlane_left_active:
        score: 1
    s_rollover_inlane_right_active:
        score: 1

