#config_version=6

  # TODO: make a working carousel for attract that shows gameover, title, and last_game_scores slides
#mode:
#  start_events: mode_attract_started
#  stop_events: mode_attract_will_stop
#  game_mode: false
#  code: mpf.modes.carousel.code.carousel.Carousel
#
#mode_settings:
#  selectable_items:
#    - gameover
#    - title
#    - last_game_scores
#  next_item_events: s_flipper_right_inactive
#  previous_item_events: s_flipper_left_inactive






slide_player:
  mode_attract_started: attract

show_player:
  mode_attract_started.1:
    attract_arrow_sweep_left:
      speed: 4
    #attract_arrow_sweep_right:
    #  speed: 4
    #attract_fivebank_sweep:
    #  speed: 4
    #attract_jet_bumpers:
    #  speed: 4
    #attract_rollover_lanes:
    #  speed: 4
    #attract_threebank_sweep:
    #  speed: 4
    #attract_top_outhole_sweep:
    #  speed: 4
    #attract_triangle_flash:
    #  speed: 4
    #
    #
    #
    #

#hardware_sound_player:
#  mode_attract_started.2:
#    "0_00.snd":
#      track: 1
#      action: play_file

