#config_version=6

#modes/rollover_lanes/config/rollover_lanes.yaml


mode:
    start_events: ball_starting
    priority: 100

show_player:
    rollover_lanes_complete:
        rollover_lanes_complete:
            speed: 4
            loops: 2
            priority: 1

shots:
    sh_rollover_upper_left:
        switch: s_rollover_upper_left
        show_tokens:
            light: l_rollover_upper_left
    sh_rollover_upper_mid:
        switch: s_rollover_upper_mid
        show_tokens:
            light: l_rollover_upper_mid
    sh_rollover_upper_right:
        switch: s_rollover_upper_right
        show_tokens:
            light: l_rollover_upper_right

shot_groups:
    rollover_lanes:
        shots:
            - sh_rollover_upper_left
            - sh_rollover_upper_mid
            - sh_rollover_upper_right
        rotate_left_events: s_jet_bumper_left_top_active, s_jet_bumper_right_mid_active
        rotate_right_events: s_jet_bumper_left_mid_active, s_jet_bumper_left_bottom_active, s_jet_bumper_right_active
        reset_events: rollover_lanes_complete
            #rollover_lanes_lit_complete: 60s

variable_player:
    # variable values defined in shot_groups
    rollover_lanes_unlit_hit:
        score: 1000 * current_player.playfield_multiplier
    rollover_lanes_lit_hit:
        score: 3000 * current_player.playfield_multiplier
    rollover_lanes_complete:
        score: 10000 * current_player.playfield_multiplier

