#config_version=6

mode:
  start_events: carousel_artist_dio_selected
  stop_events: ball_ended
  priority: 130


hardware_sound_player:
  mode_dio_started:
    "tenacious_the_metal.snd":
    #"dio_holy_diver.snd":
      track: 1
      action: play_file
      platform_options:
        loop: true
        no_cache: false
