#config_version=6

#modes/jet_bumpers/config/jet_bumpers.yaml


mode:
    start_events: ball_starting
    priority: 100

show_player:
    jet_bumpers_complete:
        jet_bumpers_complete:
            speed: 10
            loops: 2
            priority: 1

shots:
    sh_jet_bumper_left_top:
        switch: s_jet_bumper_left_top
        show_tokens:
            light: l_jet_bumper_left_top
        #reset_events: s_jet_bumper_left_top_inactive|100ms
    sh_jet_bumper_left_mid:
        switch: s_jet_bumper_left_mid
        show_tokens:
            light: l_jet_bumper_left_mid
        #reset_events: s_jet_bumper_left_mid_inactive|100ms
    sh_jet_bumper_left_bottom: # switch isnt working, so removing from shot_profile & light (it works rarely)
        switch: s_jet_bumper_left_bottom
        #show_tokens:
        #    light: l_jet_bumper_left_bottom
        #reset_events: s_jet_bumper_left_bottom_inactive|100ms
    sh_jet_bumper_right_mid:
        switch: s_jet_bumper_right_mid
        show_tokens:
            light: l_jet_bumper_right_mid
        #reset_events: s_jet_bumper_right_mid_inactive|100ms
    sh_jet_bumper_right:
        switch: s_jet_bumper_right
        show_tokens:
            light: l_jet_bumper_right
        #reset_events: s_jet_bumper_right_inactive|100ms

shot_groups:
    jet_bumpers:
        shots:
            - sh_jet_bumper_left_top
            #- sh_jet_bumper_left_bottom #switch doesnt work
            - sh_jet_bumper_left_mid
            - sh_jet_bumper_right_mid
            - sh_jet_bumper_right
        reset_events: jet_bumpers_complete

variable_player:
    # variable values defined in shot_groups
    jet_bumpers_unlit_hit:
        score: 10
    jet_bumpers_lit_hit:
        score: 15
    jet_bumpers_complete:
        score: 250

hardware_sound_player:
    s_jet_bumper_left_top_active:
        "0_1a.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false
    s_jet_bumper_left_mid_active:
        "0_1a.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false
    s_jet_bumper_left_bottom_active:
        "0_1a.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false
    s_jet_bumper_right_mid_active:
        "0_1a.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false
    s_jet_bumper_right_active:
        "0_1a.snd":
            track: 2
            action: play_file
            platform_options:
                loop: false
                no_cache: false



