#config_version=6

###############################################################################
# hardware
###############################################################################
# NOTE: with APC, switch nbr. corresponds directly to number listed in orig.
# hardware manual from manufacturer. In some Williams cases, "special solenoids
# /switches" (flippers, jet bumpers, etc.) are used. For APC, solenoids 17-22
# have switch nbrs replaced with 65-70. Right/left flippers do not have their
# button switches in mpf config, and use solenoids 23/24 respectively.
# lisy docs (Section "Hardware rules for solenoids with APC"):
#   - https://lisy.dev/swrep/LISY/LISY_user%20manual_v5.27-67a.pdf
# APC docs: https://github.com/AmokSolderer/APC/blob/master/DOC/RunGame.md


#hardware:
#  platform: lisy
#
#lisy:
#  connection: serial
#  port: /dev/ttyACM0
#  baud: 115200
#  #debug: true #will make game run slowly

##virtual configs (when not connected to physical machine)
virtual_platform_start_active_switches:
  - s_trough1_right
  - s_trough2
  - s_trough3_left


### hardware sounds

### use APC sdcard for sounds
#hardware_sound_systems:
#  default:
#    label: APC
#
## play sounds via files on APC sdcard (action name should be "<FILENAME>.SND:")
#hardware_sound_player:
#  game_start:
#    set_volume:
#      action: set_volume
#      value: 0.4
#    #"music.snd": # filename on sdcard. using "music.snd" enables using background track on orig game rom
#      track: 1
#      action: play_file
#      platform_options:
#        loop: true
#        no_cache: false
#  game_ending:
#    action: stop
#    set_volume:
#      action: set_volume
#      value: 0


###############################################################################
# game modes & player variables
###############################################################################

## modes: anything that has a folder in modes/ should be listed here
modes:
    - attract
    - base

## player variables: set the initial state of variables used by players when game starts
player_vars:
    playfield_multiplier:
        value_type: int
        initial_value: 1


###############################################################################
# switches
###############################################################################

switches:
  s_tilt_bob:
    number: 1
    ignore_window_ms: 200
    tags: tilt_warning
  s_notused1:
    number: 2
  s_start_button:
    number: 3
    tags: start
  s_coin_chute_right:
    number: 4
  s_coin_chute_mid: #not used in US config
    number: 5
  s_coin_chute_left:
    number: 6
  s_tilt_slam:
    number: 7
  s_high_score_reset:
    number: 8
  s_tilt_playfield:
    number: 9
  s_drain:
    number: 10
  s_trough1_right:
    number: 11
  s_trough2:
    number: 12
  s_trough3_left:
    number: 13
  s_inlane_right_inner:
    number: 14
    tags: playfield_active
  s_inlane_right_outer:
    number: 15
    tags: playfield_active
  s_outlane_right:
    number: 16
    tags: playfield_active
  s_outlane_left:
    number: 17
    tags: playfield_active
  s_inlane_left:
    number: 18
    tags: playfield_active
  s_standup_left:
    number: 19
    tags: playfield_active
  s_ball_popper:
    number: 20
  s_standup_right_top:
    number: 21
    tags: playfield_active
  s_standup_right_bottom:
    number: 22
    tags: playfield_active
  s_standup_captive_ball:
    number: 23
    tags: playfield_active
  s_standup_right_50k:
    number: 24
    tags: playfield_active
  s_bldg_height1:
    number: 25
  s_bldg_height2:
    number: 26
  s_threebank_left:
    number: 27
    tags: playfield_active
  s_threebank_mid:
    number: 28
    tags: playfield_active
  s_threebank_right:
    number: 29
    tags: playfield_active
  s_standup_ramp:
    number: 30
    tags: playfield_active
  s_loop_right:
    number: 31
    tags: playfield_active
  s_loop_left:
    number: 32
    tags: playfield_active
  s_onramp_loop_low:
    number: 33
    tags: playfield_active
  s_onramp_loop_mid:
    number: 34
    tags: playfield_active
  s_onramp_loop_high:
    number: 35
    tags: playfield_active
  s_onramp_bypass:
    number: 36
    tags: playfield_active
  s_vuk_upper:
    number: 37
  s_subway1:
    number: 38
    tags: playfield_active
  s_subway2:
    number: 39
    tags: playfield_active
  s_vuk_subway:
    number: 40
  s_spinner:
    number: 41
    tags: playfield_active
  s_diverter_open:
    number: 42
  s_ramp_right_entry:
    number: 43
    tags: playfield_active
  s_ramp_center_entry:
    number: 44
    tags: playfield_active
  s_ramp_center_mid:
    number: 45
    tags: playfield_active
  s_ramp_center_exit:
    number: 46
    tags: playfield_active
  s_notused2:
    number: 47
  s_notused3:
    number: 48
  s_notused4:
    number: 49
  s_plunger:
    number: 50
  s_notused5:
    number: 51
  s_pop_bumper_left:
    number: 52
  s_pop_bumper_right:
    number: 53
  s_pop_bumper_top:
    number: 54
  s_slingshot_left:
    number: 55
  s_slingshot_right:
    number: 56
  s_flipper_right_lane_change:
    number: 57
  s_flipper_left_lane_change:
    number: 58
  s_notused6:
    number: 59
  s_notused7:
    number: 60
  s_notused8:
    number: 61
  s_notused9:
    number: 62
  s_notused10:
    number: 63
  s_notused11:
    number: 64

  ### flipper coils hardwired via "special solenoid" & APC/lisy uses hardware
  ### rules, switch config not needed.
  s_flipper_left:
      number:
      tags: left_flipper
  s_flipper_right:
      number:
      tags: right_flipper


################################################################################
# coils/solenoids
################################################################################

coils:
  c_drain_eject:
    number: 1 #listed as 1a in manual. 1c is captive ball flashers
    #default_pulse_ms: 20
  c_trough_eject:
    number: 2 #2a in manual (shooter ln feeder). 2c is center ramp1+bldg flashers
    #default_pulse_ms: 20
  c_threebank_reset:
    number: 3 #3a in manual. 3c is ctr ramp2+spinner flashers
  c_diverter:
    number: 4 #4a in manual. 4c is ctr ramp3 flasher
  c_ball_popper:
    number: 5 #5a in manual. 5c is ctr ramp4 flasher
  c_vuk_subway:
    number: 6 #6a in manual. 6c is right ramp1 flasher
  c_knocker:
    number: 7 #7a in manual. 7c is right ramp2 flasher
  c_notused:
    number: 8 #8a in manual. 8c is right ramp3 flashers
  c_notused2: #building motor + relay in Earthshaker manual
    number: 9
  c_playfield_upper_gi_relay:
    number: 10
  c_insert_board_gi_relay:
    number: 11
  c_ac_select_relay:
    number: 12
  c_vuk_upper:
    number: 13
  c_jackpot_flasher:
    number: 14
  c_playfield_lower_gi_relay:
    number: 15
  c_onramp_pop_bumper_flashers:
    number: 16
  c_pop_bumper_left:
    number: 17
  c_slingshot_left:
    number: 18
  c_pop_bumper_right:
    number: 19
  c_slingshot_right:
    number: 20
  c_pop_bumper_top:
    number: 21
  c_shaker_motor:
    number: 22

  c_flipper_right:
    number: 23
  c_flipper_left:
    number: 24


################################################################################
# lights
################################################################################

lights:
  l_captive_ball1_bottom:
    number: 1
  l_captive_ball2:
    number: 2
  l_captive_ball3:
    number: 3
  l_captive_ball4:
    number: 4
  l_captive_ball5_top:
    number: 5
  l_captive_ball_arrow:
    number: 6
  l_spinner:
    number: 7
  l_pop_bumper_center:
    number: 8
  l_bonus_2x:
    number: 9
  l_bonus_3x:
    number: 10
  l_bonus_4x:
    number: 11
  l_bonus_5x:
    number: 12
  l_bonus_6x_exball:
    number: 13
  l_bonus_6x_spec:
    number: 14
  l_return_lane:
    number: 15
  l_outlane_left:
    number: 16
  l_building7:
    number: 17
  l_building8:
    number: 18
  l_building9:
    number: 19
  l_building4:
    number: 20
  l_building5:
    number: 21
  l_building6:
    number: 22
  l_building1:
    number: 23
  l_building2:
    number: 24
  l_building3:
    number: 25
  l_standup_right_top:
    number: 26
  l_standup_right_bottom:
    number: 27
  l_standup_right_50k:
    number: 28
  l_inlane_right_inner:
    number: 29
  l_inline_right_outer:
    number: 30
  l_outlane_right:
    number: 31
  l_ballsave:
    number: 32
  l_miles1:
    number: 33
  l_miles2:
    number: 34
  l_miles3:
    number: 35
  l_miles4:
    number: 36
  l_miles5:
    number: 37
  l_miles10:
    number: 38
  l_miles20:
    number: 39
  l_miles30:
    number: 40
  l_pop_bumper_top:
    number: 41
  l_pop_bumper_left:
    number: 42
  l_pop_bumper_right:
    number: 43
  l_ramp_right_jackpot:
    number: 44
  l_ramp_right_lock:
    number: 45
  l_ramp_right_3miles:
    number: 46
  l_ramp_center_100k:
    number: 47
  l_ramp_center_2miles:
    number: 48
  l_roadsign_left:
    number: 49
  l_standup_left:
    number: 50
  l_ball_popper_lock:
    number: 51
  l_ball_popper_top:
    number: 52
  l_standup_center:
    number: 53
  l_drophole_extraball:
    number: 54
  l_drophole_lock:
    number: 55
  l_fault_loop:
    number: 56
  l_roadsign_right:
    number: 57
  l_backbox_jackpot1_left:
    number: 58
  l_backbox_jackpot2:
    number: 59
  l_backbox_jackpot3:
    number: 60
  l_backbox_jackpot4:
    number: 61
  l_backbox_jackpot5:
    number: 62
  l_backbox_jackpot6:
    number: 63
  l_backbox_jackpot7_right:
    number: 64


################################################################################
# playfield details/devices
################################################################################

## ball devices
## (anything that holds & releases a ball, including the playfield which "holds
## a ball". trough, the plunger lane, VUKs, poppers, playfield locks, etc.)

ball_devices:

  ## plunger. config for manual plunge
  bd_plunger_lane:
    ball_switches: s_plunger
    mechanical_eject: true
    eject_timeouts: 5s

  ## trough. ball is kicked from drain/outhole to trough
  bd_trough:
    ball_switches:
      - s_trough1_right
      - s_trough2
      - s_trough3_left
    eject_coil: c_trough_eject
    tags: home, trough
    eject_timeouts: 3s
    eject_targets: bd_plunger_lane

  ## drain/outhole (used with older 3+ ball games). ball leaves playfield to here
  bd_drain:
    ball_switches: s_drain
    eject_coil: c_drain_eject
    eject_targets: bd_trough
    tags: drain

  # left playfield ball popper
  bd_ball_popper_left:
    ball_switches: s_ball_popper
    eject_coil: c_ball_popper
    eject_timeouts: 3s

  # upper right playfield vuk
  bd_vuk_upper:
    ball_switches: s_vuk_upper
    eject_coil: c_vuk_upper
    eject_timeouts: 3s

  # lower right subway vuk
  bd_vuk_subway:
    ball_switches: s_vuk_subway
    eject_coil: c_vuk_subway
    eject_timeouts: 3s


## main playfield & any other minor playfields
playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger_lane


## autofire coils (things that fire immediately when switch is hit)
autofire_coils:
  slingshot_left:
    coil: c_slingshot_left
    switch: s_slingshot_left
  slingshot_right:
    coil: c_slingshot_right
    switch: s_slingshot_right
  pop_bumper_left:
    coil: c_pop_bumper_left
    switch: s_pop_bumper_left
  pop_bumper_right:
    coil: c_pop_bumper_right
    switch: s_pop_bumper_right
  pop_bumper_top:
    coil: c_pop_bumper_top
    switch: s_pop_bumper_top

## diverters. anything that changes a ball's path
## things like ramp changes & magnets /control gates & posts/trap doors/ringmaster
diverters:
  div_ramp_vs_subway:
    activation_coil: c_diverter
    type: hold


################################################################################
## displays
################################################################################

## segment displays
#segment_displays:
#  segment_display_top:
#    number: 1
#    platform: lisy
#    #size: TBD
#  segment_display_bottom:
#    number: 2
#    platform: lisy
#
#segment_display_player:
#  # game start
#  game_start:
#    segment_display_top:
#      text: "{current_player.ball:d}"
#    segment_display_bottom:
#      text: ""
#
#  # show score when adding players
#  player_added.1{num==1}:
#    segment_display_top:
#      text: "{players[0].score:d}"
#  player_added.2{num==2}:
#    segment_display_top:
#      text: "{players[1].score:d}"
#  player_added.3{num==3}:
#    segment_display_bottom:
#      text: "{players[2].score:d}"
#  player_added.4{num==4}:
#    segment_display_bottom:
#      text: "{players[3].score:d}"
#
#  # clear only info display after game
#  game_ended:
#    #info_display:
#    #  text: ""
#  game_ended{machine.player1_score > 0}:
#    segment_display_top:
#      text: "{machine.player1_score:d}"
#  game_ended{machine.player2_score > 0}:
#    segment_display_top:
#      text: "{machine.player2_score:d}"
#  game_ended{machine.player3_score > 0}:
#    segment_display_bottom:
#      text: "{machine.player3_score:d}"
#  game_ended{machine.player4_score > 0}:
#    segment_display_bottom:
#      text: "{machine.player4_score:d}"
#
#  #flash display on player turn
#  player_turn_started.1{number==1}:
#    segment_display_top:
#      action: flash
#  player_turn_ended.2{number==1}:
#    segment_display_top:
#      action: no_flash
#  player_turn_started.3{number==2}:
#    segment_display_top:
#      action: flash
#  player_turn_ended.4{number==2}:
#    segment_display_top:
#      action: no_flash
#  player_turn_started.5{number==3}:
#    segment_display_bottom:
#      action: flash
#  player_turn_ended.6{number==3}:
#    segment_display_bottom:
#      action: no_flash
#  player_turn_started.7{number==4}:
#    segment_display_bottom:
#      action: flash
#  player_turn_ended.8{number==4}:
#    segment_display_bottom:
#      action: no_flash





